// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwMQetk9_mR3bXKklPvJ51XKpGYLbcwmQ',
    appId: '1:226213579014:web:c851a0600c00090bb0f687',
    messagingSenderId: '226213579014',
    projectId: 'myinventory-aee3c',
    authDomain: 'myinventory-aee3c.firebaseapp.com',
    storageBucket: 'myinventory-aee3c.appspot.com',
    measurementId: 'G-S95555DJ2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJ9PwarrznJ9827Na3lpBi_LSuvhBBUA',
    appId: '1:226213579014:android:0f28ac544525deedb0f687',
    messagingSenderId: '226213579014',
    projectId: 'myinventory-aee3c',
    storageBucket: 'myinventory-aee3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6rfu_HLicLvp9K1HTx6QiGEl8BbELyJw',
    appId: '1:226213579014:ios:8b49bb7a5b803d39b0f687',
    messagingSenderId: '226213579014',
    projectId: 'myinventory-aee3c',
    storageBucket: 'myinventory-aee3c.appspot.com',
    iosBundleId: 'com.example.myInventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6rfu_HLicLvp9K1HTx6QiGEl8BbELyJw',
    appId: '1:226213579014:ios:8b49bb7a5b803d39b0f687',
    messagingSenderId: '226213579014',
    projectId: 'myinventory-aee3c',
    storageBucket: 'myinventory-aee3c.appspot.com',
    iosBundleId: 'com.example.myInventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwMQetk9_mR3bXKklPvJ51XKpGYLbcwmQ',
    appId: '1:226213579014:web:6a5596bcaf05d1dfb0f687',
    messagingSenderId: '226213579014',
    projectId: 'myinventory-aee3c',
    authDomain: 'myinventory-aee3c.firebaseapp.com',
    storageBucket: 'myinventory-aee3c.appspot.com',
    measurementId: 'G-HNJS6F52KC',
  );
}
